module.exports = {
	useBanner: require('./banner/use-banner'),
	useCleaner: require('./clean/use-cleaner.js'),
	useCompression: require('./compression/use-compression'),
	useDevServer: require('./devServer/use-dev-server'),
	useFaviconGenerator: require('./favicon/use-favicon-generator'),
	useFontLoader: require('./font/use-font-loader'),
	useSourceMaps: require('./sourceMaps/use-source-maps'),
	useHotModuleReplacement: require('./hot/use-hot-module-replacement'),
	useHtmlTemplate: require('./html/use-html-template'),
	useImageLoader: require('./image/use-image-loader'),
	useSvgLoader: require('./image/use-svg-loader'),
	useApplicationManifest: require('./manifest/use-application-manifest'),
	useChunk: require('./optimize/use-chunks'),
	useExtendedAPI: require('./optimize/use-extended-API'),
	useHashedModule: require('./optimize/use-hashed-module'),
	useModuleConcatenation: require('./optimize/use-module-concatenation'),
	usePerformance: require('./optimize/use-performance'),
    useTypescriptLoader: require('./typescript/use-typescript-loader'),
    useTypescriptLinter: require('./linter/use-typescript-linter'),
    useTypescriptTypeChecker: require('./typescript/use-typescript-type-checker'),
	useLoadLanguages: require('./internacionalization/use-load-languages'),
	reportAnalyzer: require('./report/report-analyzer')
};
